### ISSUE TITLE
SidebarGUIPlugin v4.6.4 will not load with Cura 5.7.0 Beta1

### ISSUE THREAD

**Issue by DivingDuck** [fieldOfView/Cura-SidebarGUIPlugin#46] opened 2024-03-18 14:47 UTC
Hi @fieldOfView,
I hope, you are well.

FYI and if you find a little bit time :)
I give the new 5.7.0beta1 a quick test and took a look in the cura log as two of your plugins will not load with the beta. While loading was an easy manipullation for testing, there are still some warnings in the log for this plug in and for TabbedSettingsPlugin.

I attached my log file for further information. It includes two starts, one for the installation of cura 5.7.0beta1 and one after I manipulate the version compatibility for the two plugins. In addition I also fix my printer def files for metadata setting version so that this don't show up again.

Best regards,
DD

 
[cura.zip](https://github.com/fieldOfView/Cura-SidebarGUIPlugin/files/14637787/cura.zip)

**Comment by fieldOfView** [comment] 2024-03-19 06:00
Closing as a duplicate of https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/31

**Closed** 2024-03-19 06:00 UTC
