### ISSUE TITLE
Cura 5.1/5.2

### ISSUE THREAD

**Issue by WimVDK** [fieldOfView/Cura-SidebarGUIPlugin#40] opened 2022-10-23 16:56 UTC
Due to high energy prices my 3d printing was a bit on the sideburner (still is) but i'm updating things atm. Just updated to cura 5.2 and tried to reinstall the sidebar GUI. The official released one 4.4.0 still isn't compatible, however i noticed a 4.4.1 DEV version under releases that's dated about a week ago. However its in .curapackage, never used that before. Can you elaborate on how i can update to the dev version?

**Comment by dcervenkov** [comment] 2022-10-24 08:36
[Apparently](https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/31#issuecomment-1179494228) you just drag & drop the .curapackage on the build plate like you would an STL file.

**Comment by fieldOfView** [comment] 2022-10-24 08:50
What @dcervenkov says.

The new version has been submitted to the Marketplace for a couple of weeks now, but it is still in the review queue at Ultimaker.

I'm closing this as a duplicate of https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/31

**Closed by fieldOfView** 2022-10-24 08:50 UTC
